name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-job-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build project with Webpack
      run: npx webpack --config webpack.config.js

    - name: Deploy to Render
      run: |
        echo "Initiating deployment to Render..."
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          "https://api.render.com/deploy/srv-co0i526d3nmc73f7ncq0?key=${{ secrets.RENDER_API_KEY }}")

        echo "HTTP Response Code: $RESPONSE"
        echo "Render API Response:"
        cat response.json

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Deployment failed!"
          echo "Error details from Render API:"
          cat response.json
          exit 1
        else
          echo "Deployment succeeded!"
        fi
