name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x' # Specify the Node.js version for deployment

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npx webpack

    - name: Deploy to Render
      run: |
        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
        https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)

        echo "Render API response: $RESPONSE"

        if [[ $RESPONSE != *"successful"* ]]; then
          echo "Deployment failed!" >&2
          exit 1
        fi

