name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-job-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Wait for Previous Job
      run: |
        echo "Checking for existing jobs in progress..."
        MAX_RETRIES=5
        WAIT_TIME=30 # seconds

        for ((i=1; i<=MAX_RETRIES; i++)); do
          STATUS=$(gh run list --repo ${{ github.repository }} --branch ${{ github.ref_name }} --status in_progress | wc -l)
          if [ "$STATUS" -eq 0 ]; then
            echo "No jobs in progress. Proceeding with deployment."
            break
          fi

          if [ "$i" -eq "$MAX_RETRIES" ]; then
            echo "Timeout: Previous job did not finish in time." >&2
            exit 1
          fi

          echo "Job in progress. Retrying in $WAIT_TIME seconds..."
          sleep $WAIT_TIME
        done

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Deploy to Render
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          "https://api.render.com/deploy/srv-co0i526d3nmc73f7ncq0?key=${{ secrets.RENDER_API_KEY }}")

        echo "HTTP Response Code: $RESPONSE"
        echo "Render API Response:"
        cat response.json

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Deployment failed!" >&2
          exit 1
        fi

