name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-job-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Attempt to download build artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: build  # Match the artifact name in webpack.yml
      continue-on-error: true  # Allow the workflow to continue if artifact is missing

    - name: Check if artifact exists
      id: artifact-check
      run: |
        if [ ! -d "build" ]; then
          echo "Artifact not found. Setting 'needs_build' to true."
          echo "needs_build=true" >> $GITHUB_ENV
        else
          echo "Artifact found. Proceeding with deployment."
          echo "needs_build=false" >> $GITHUB_ENV
        fi

    - name: Build project (if artifact is missing)
      if: env.needs_build == 'true'
      run: |
        echo "Building the project since artifact is missing..."
        npm ci
        npx webpack

    - name: Deploy to Render
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          "https://api.render.com/deploy/srv-co0i526d3nmc73f7ncq0?key=${{ secrets.RENDER_API_KEY }}")

        echo "HTTP Response Code: $RESPONSE"
        echo "Render API Response:"
        cat response.json

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Deployment failed!" >&2
          exit 1

