name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-job-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Attempt to download build artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        name: build  # Artifact name from webpack.yml
      continue-on-error: true  # Workflow bypass if artifact is missing

    - name: Check if artifact exists
      id: artifact-check
      run: |
        if [ ! -d "build" ]; then
          echo "Artifact not found. Setting 'needs_build' to true."
          echo "needs_build=true" >> $GITHUB_ENV
        else
          echo "Artifact found. Proceeding with deployment."
          echo "needs_build=false" >> $GITHUB_ENV
        fi

    - name: Build project (if artifact is missing)
      if: env.needs_build == 'true'
      run: |
        echo "Building the project since artifact is missing..."
        npm ci
        npx webpack --config webpack.config.js

    - name: Deploy to Render
      run: |
        echo "Initiating deployment to Render..."
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}")

        echo "HTTP Response Code: $RESPONSE"
        echo "Render API Response:"
        cat response.json

        if [[ "$RESPONSE" =~ ^2[0-9][0-9]$ ]]; then
          echo "Deployment succeeded!"
        else
          echo "Deployment failed!"
          echo "Error details from Render API:"
          cat response.json
          exit 1
        fi
