name: Deploy

on:
  workflow_run:
    workflows: ["NodeJS with Webpack"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x' # Specify the Node.js version for deployment

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npx webpack

    - name: Deploy to Render
      id: deploy_to_render
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          "https://api.render.com/deploy/srv-co0i526d3nmc73f7ncq0?key=${{ secrets.RENDER_API_KEY }}")

        echo "HTTP Response Code: $RESPONSE"
        echo "Render API Response:"
        cat response.json

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Deployment failed!" >&2
          exit 1
        fi


