name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: webpack-build-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project with Webpack
      run: npx webpack

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build  # Name of artifact
        path: build  # Build directory


